[{"owner":{"profile_image":"https://www.gravatar.com/avatar/fd2bfef83bc07bfe03aeb5f0ef08dc03?s=256&d=identicon&r=PG","account_id":1322512,"user_type":"registered","user_id":1268003,"link":"https://stackoverflow.com/users/1268003/martin-andersson","reputation":18477,"display_name":"Martin Andersson","accept_rate":82},"content_license":"CC BY-SA 4.0","score":0,"post_id":72598626,"edited":false,"creation_date":1675225609,"comment_id":132880846,"body":"In my opinion it is not &quot;just fine&quot; but could be elegant? <code>@throws SomeException enumerating many conditions, is noise, can be misunderstood as only one condition, and certainly makes the last conditions easy to miss</code>, but having <code>@throws SameException listed once</code> and <code>@throws SameException twice</code> brings attention to unique conditions. I ended my first sentence with a question mark because I am like many others biased by our culture and habits."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/0ff652685122f4500dd4f3c21fb32da2?s=256&d=identicon&r=PG","account_id":36734,"user_type":"registered","user_id":104891,"link":"https://stackoverflow.com/users/104891/crazycoder","reputation":392137,"display_name":"CrazyCoder"},"content_license":"CC BY-SA 4.0","score":0,"post_id":72576694,"edited":false,"creation_date":1654878019,"comment_id":128205445,"body":"Dependency is not enough, you need to use a plug-in with javac2 goal to build the forms, see <a href=\"https://stackoverflow.com/a/69258838/104891\">stackoverflow.com/a/69258838/104891</a>."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/a771ce5c75531b9171379df1e7429c87?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":17400576,"user_type":"registered","user_id":12609542,"link":"https://stackoverflow.com/users/12609542/david-blbulyan","reputation":35,"display_name":"David Blbulyan"},"content_license":"CC BY-SA 4.0","score":0,"post_id":72576694,"reply_to_user":{"profile_image":"https://www.gravatar.com/avatar/0ff652685122f4500dd4f3c21fb32da2?s=256&d=identicon&r=PG","account_id":36734,"user_type":"registered","user_id":104891,"link":"https://stackoverflow.com/users/104891/crazycoder","reputation":392137,"display_name":"CrazyCoder"},"edited":false,"creation_date":1654877845,"comment_id":128205368,"body":"I added com.jetbrains.intellij.java:java-gui-forms-rt like dependency from repository <a href=\"https://www.jetbrains.com/intellij-repository/releases\" rel=\"nofollow noreferrer\">jetbrains.com/intellij-repository/releases</a> but it din&#39;t fix my problem"},{"owner":{"profile_image":"https://www.gravatar.com/avatar/a771ce5c75531b9171379df1e7429c87?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":17400576,"user_type":"registered","user_id":12609542,"link":"https://stackoverflow.com/users/12609542/david-blbulyan","reputation":35,"display_name":"David Blbulyan"},"content_license":"CC BY-SA 4.0","score":0,"post_id":72576694,"reply_to_user":{"profile_image":"https://www.gravatar.com/avatar/0ff652685122f4500dd4f3c21fb32da2?s=256&d=identicon&r=PG","account_id":36734,"user_type":"registered","user_id":104891,"link":"https://stackoverflow.com/users/104891/crazycoder","reputation":392137,"display_name":"CrazyCoder"},"edited":false,"creation_date":1654875590,"comment_id":128204568,"body":"I also added a dependency in my pom.xml: &lt;dependency&gt;             &lt;groupId&gt;com.intellij&lt;/groupId&gt;             &lt;artifactId&gt;forms_rt&lt;/artifactId&gt;             &lt;version&gt;7.0.3&lt;/version&gt;         &lt;/dependency&gt;"},{"owner":{"profile_image":"https://www.gravatar.com/avatar/0ff652685122f4500dd4f3c21fb32da2?s=256&d=identicon&r=PG","account_id":36734,"user_type":"registered","user_id":104891,"link":"https://stackoverflow.com/users/104891/crazycoder","reputation":392137,"display_name":"CrazyCoder"},"content_license":"CC BY-SA 4.0","score":0,"post_id":72576694,"edited":false,"creation_date":1654875489,"comment_id":128204521,"body":"Please see <a href=\"https://youtrack.jetbrains.com/issue/IDEA-151118/Offical-maven-plugin-for-IntelliJ-GUI-Designer\" rel=\"nofollow noreferrer\">youtrack.jetbrains.com/issue/IDEA-151118/&hellip;</a>."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/a771ce5c75531b9171379df1e7429c87?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":17400576,"user_type":"registered","user_id":12609542,"link":"https://stackoverflow.com/users/12609542/david-blbulyan","reputation":35,"display_name":"David Blbulyan"},"content_license":"CC BY-SA 4.0","score":0,"post_id":72576694,"reply_to_user":{"profile_image":"https://www.gravatar.com/avatar/0ff652685122f4500dd4f3c21fb32da2?s=256&d=identicon&r=PG","account_id":36734,"user_type":"registered","user_id":104891,"link":"https://stackoverflow.com/users/104891/crazycoder","reputation":392137,"display_name":"CrazyCoder"},"edited":false,"creation_date":1654875443,"comment_id":128204503,"body":"I use maven, it&#39;s maven project in intellij-idea"},{"owner":{"profile_image":"https://www.gravatar.com/avatar/0ff652685122f4500dd4f3c21fb32da2?s=256&d=identicon&r=PG","account_id":36734,"user_type":"registered","user_id":104891,"link":"https://stackoverflow.com/users/104891/crazycoder","reputation":392137,"display_name":"CrazyCoder"},"content_license":"CC BY-SA 4.0","score":0,"post_id":72576694,"edited":false,"creation_date":1654875281,"comment_id":128204434,"body":"How do you compile/build the jar file? Do you use Maven/Gradle?"},{"owner":{"profile_image":"https://i.stack.imgur.com/K1mTV.jpg?s=256&g=1","account_id":969721,"user_type":"registered","user_id":992484,"link":"https://stackoverflow.com/users/992484/madprogrammer","reputation":344527,"display_name":"MadProgrammer","accept_rate":60},"content_license":"CC BY-SA 4.0","score":0,"post_id":72552971,"edited":false,"creation_date":1654729427,"comment_id":128164242,"body":"<code>Scanner#hasNextInt</code>"},{"owner":{"profile_image":"https://www.gravatar.com/avatar/31dcfef154edd75223ae28f2cfd77f71?s=256&d=identicon&r=PG","account_id":69443,"user_type":"registered","user_id":202009,"link":"https://stackoverflow.com/users/202009/andy-thomas","reputation":85343,"display_name":"Andy Thomas","accept_rate":79},"content_license":"CC BY-SA 4.0","score":1,"post_id":72546743,"edited":false,"creation_date":1654696806,"comment_id":128153074,"body":"You can get an OutOfMemoryError if you try to allocate more heap space than is available. But you can also get it if you cause the VM or native code to run out of memory. When that happens, the VM can no longer guarantee that your code will run as expected -- including any attempt by code running atop the VM to recover from an error inside the VM."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/70c1879f44999635c08c349a03e8319a?s=256&d=identicon&r=PG","account_id":1041528,"user_type":"registered","user_id":1047469,"link":"https://stackoverflow.com/users/1047469/marthursson","reputation":3262,"display_name":"marthursson"},"content_license":"CC BY-SA 4.0","score":0,"post_id":72546743,"edited":false,"creation_date":1654696386,"comment_id":128152868,"body":"You should generally avoid catching ANY exceptions in application code if you don&#39;t think there&#39;s anything you can do to fix the problem. Cleanup (like your example try/finally) is a different thing: Note that it doesn&#39;t rely on catching the exception or error, you&#39;re just making sure that you always attempt to clean up critical resources. The finally block will always be executed, even on an Error."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/7684a686e233476c6713ced10a9cef41?s=256&d=identicon&r=PG","account_id":74704,"user_type":"registered","user_id":214525,"link":"https://stackoverflow.com/users/214525/f1sh","reputation":11534,"display_name":"f1sh","accept_rate":100},"content_license":"CC BY-SA 4.0","score":2,"post_id":72546743,"edited":false,"creation_date":1654696026,"comment_id":128152714,"body":"Comparing a <code>OutOfMemoryError</code> to a <code>ArrayIndexOutOfBoundsException</code> is a stretch to say the least. And of course any Exception can leave your application in a weird state (like your example with the locks), but it is up to you to write your code in a way to prevent this. Any <code>Error</code> (which is different than an Exception!) is usually thrown by the VM itself and signals &quot;something really messed up, don&#39;t handle me&quot;. An <code>OutOfMemoryError</code> is special because even if you tried handling it (like logging), there might not be any memory left for even the simplest task."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/7d4357beb6de2712b6b2171ebe4c499b?s=256&d=identicon&r=PG","account_id":3023214,"user_type":"registered","user_id":2563754,"link":"https://stackoverflow.com/users/2563754/seelenvirtuose","reputation":20361,"display_name":"Seelenvirtuose"},"content_license":"CC BY-SA 4.0","score":2,"post_id":72546743,"edited":false,"creation_date":1654695791,"comment_id":128152600,"body":"First there is a difference between <i>errors</i> and <i>exceptions.</i>. Additionally, among errors the <code>OutOfMemoryError</code> is a special thing."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/f7cf53bd8e67338b36d086f48477edfa?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":22531657,"user_type":"registered","user_id":16723586,"link":"https://stackoverflow.com/users/16723586/kiznet007","reputation":15,"display_name":"Kiznet007"},"content_license":"CC BY-SA 4.0","score":0,"post_id":70008079,"edited":false,"creation_date":1637200282,"comment_id":123765233,"body":"This is good to know."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/f914cd02166793195d9d950503f8f739?s=256&d=identicon&r=PG","account_id":1352170,"user_type":"registered","user_id":1291492,"link":"https://stackoverflow.com/users/1291492/controlaltdel","reputation":34246,"display_name":"ControlAltDel","accept_rate":100},"content_license":"CC BY-SA 4.0","score":0,"post_id":70008079,"edited":false,"creation_date":1637169188,"comment_id":123756047,"body":"And honestly, HTML 5 is IMO the source for the best way to deal with bad user input. The INPUT tag has really useful functionality for setting attributes to define what is permissible (checked when the FORM is submitted). This is really the state of the art at the end of 2021. It&#39;s much harder to do in Java / with try { } catch"},{"owner":{"profile_image":"https://www.gravatar.com/avatar/f914cd02166793195d9d950503f8f739?s=256&d=identicon&r=PG","account_id":1352170,"user_type":"registered","user_id":1291492,"link":"https://stackoverflow.com/users/1291492/controlaltdel","reputation":34246,"display_name":"ControlAltDel","accept_rate":100},"content_license":"CC BY-SA 4.0","score":0,"post_id":70008079,"edited":false,"creation_date":1637168845,"comment_id":123755908,"body":"If you go on to be a professional coder, you aren&#39;t likely to deal with problems like this. Using Scanner on the command line is mostly just for practice. I am a big proponent of &quot;fast fail&quot; where you give up on what you are doing early, and show the user a good error message (or log it to a file). There are some kinds of Exceptions you can recover from, but a lot of times bad input (if you can&#39;t ask the user to re-enter) is fatal"},{"owner":{"profile_image":"https://www.gravatar.com/avatar/9902ba6e4ff2e80c753aa5c73b1f757b?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":7821678,"user_type":"registered","user_id":5914654,"link":"https://stackoverflow.com/users/5914654/vincrichaud","reputation":2208,"display_name":"vincrichaud"},"content_license":"CC BY-SA 4.0","score":0,"post_id":70008079,"edited":false,"creation_date":1637166443,"comment_id":123754788,"body":"Separate try-catch seems to be a good solution here"},{"owner":{"profile_image":"https://i.stack.imgur.com/ojvZh.jpg?s=256&g=1","account_id":1316033,"user_type":"registered","user_id":1262865,"link":"https://stackoverflow.com/users/1262865/john16384","reputation":7855,"display_name":"john16384","accept_rate":50},"content_license":"CC BY-SA 4.0","score":0,"post_id":69944374,"reply_to_user":{"profile_image":"https://www.gravatar.com/avatar/1233ec65168f4aae4d939ae8fe6cde1e?s=256&d=identicon&r=PG","account_id":36137,"user_type":"registered","user_id":102937,"link":"https://stackoverflow.com/users/102937/robert-harvey","reputation":178809,"display_name":"Robert Harvey","accept_rate":90},"edited":false,"creation_date":1636750931,"comment_id":123649326,"body":"Perhaps you may want to choose a different venue for this discussion, I&#39;ve already made up my mind on this."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/1233ec65168f4aae4d939ae8fe6cde1e?s=256&d=identicon&r=PG","account_id":36137,"user_type":"registered","user_id":102937,"link":"https://stackoverflow.com/users/102937/robert-harvey","reputation":178809,"display_name":"Robert Harvey","accept_rate":90},"content_license":"CC BY-SA 4.0","score":0,"post_id":69944374,"edited":false,"creation_date":1636737874,"comment_id":123645152,"body":"Perhaps your logic is backwards.  <a href=\"https://www.baeldung.com/java-checked-unchecked-exceptions\" rel=\"nofollow noreferrer\">This</a> states: <i>“If a client can reasonably be expected to recover from an exception, make it a checked exception. If a client cannot do anything to recover from the exception, make it an unchecked exception.”</i>"},{"owner":{"profile_image":"https://www.gravatar.com/avatar/1233ec65168f4aae4d939ae8fe6cde1e?s=256&d=identicon&r=PG","account_id":36137,"user_type":"registered","user_id":102937,"link":"https://stackoverflow.com/users/102937/robert-harvey","reputation":178809,"display_name":"Robert Harvey","accept_rate":90},"content_license":"CC BY-SA 4.0","score":0,"post_id":69944374,"edited":false,"creation_date":1636736006,"comment_id":123644505,"body":"Hmm... Lets check that assumption (no pun intended): <a href=\"https://docs.oracle.com/javase/9/docs/api/java/io/FileNotFoundException.html\" rel=\"nofollow noreferrer\">FileNotFoundException</a> is a checked exception, even though it could easily be solved by providing the correct file name."},{"owner":{"profile_image":"https://i.stack.imgur.com/ojvZh.jpg?s=256&g=1","account_id":1316033,"user_type":"registered","user_id":1262865,"link":"https://stackoverflow.com/users/1262865/john16384","reputation":7855,"display_name":"john16384","accept_rate":50},"content_license":"CC BY-SA 4.0","score":0,"post_id":69944374,"reply_to_user":{"profile_image":"https://www.gravatar.com/avatar/1233ec65168f4aae4d939ae8fe6cde1e?s=256&d=identicon&r=PG","account_id":36137,"user_type":"registered","user_id":102937,"link":"https://stackoverflow.com/users/102937/robert-harvey","reputation":178809,"display_name":"Robert Harvey","accept_rate":90},"edited":false,"creation_date":1636733918,"comment_id":123643616,"body":"Perhaps that is worded a bit poorly.  It means you should declare an exception as checked only if callers can&#39;t prevent the exceptional situation from happening, and neither could the code that throws it.  If callers can easily prevent the problem (by passing in correct parameters for example) then it shouldn&#39;t be checked.  If throwers can easily handle the case, then they shouldn&#39;t be throwing anything at all.  An <code>IOException</code> is something that is outside the control of both the caller and the throwing code because external systems are involved."},{"owner":{"profile_image":"https://lh4.googleusercontent.com/-XO5pmVBQa3Y/AAAAAAAAAAI/AAAAAAAAAAA/AMZuucnEnwT2r9D_vvE0tEkG_cwkXTZaXg/photo.jpg?sz=256","account_id":18554741,"user_type":"registered","user_id":13520144,"link":"https://stackoverflow.com/users/13520144/brunner-arthur","reputation":1,"display_name":"Brunner Arthur"},"content_license":"CC BY-SA 4.0","score":0,"post_id":69935845,"edited":false,"creation_date":1636732926,"comment_id":123643202,"body":"thanks Annikov for your suggestion.  I just solved the problem. After 3 days without sleep(not even for 5 minutes), trying to solve this problem so that I can make enough money to rent a place"},{"owner":{"profile_image":"https://www.gravatar.com/avatar/1233ec65168f4aae4d939ae8fe6cde1e?s=256&d=identicon&r=PG","account_id":36137,"user_type":"registered","user_id":102937,"link":"https://stackoverflow.com/users/102937/robert-harvey","reputation":178809,"display_name":"Robert Harvey","accept_rate":90},"content_license":"CC BY-SA 4.0","score":0,"post_id":69944374,"edited":false,"creation_date":1636730739,"comment_id":123642260,"body":"What does &quot;Exceptions should only be checked when they&#39;re out of control of both the caller and receiver&quot; mean?"},{"owner":{"profile_image":"https://i.stack.imgur.com/shfxy.jpg?s=256&g=1","account_id":8604130,"user_type":"registered","user_id":6444776,"link":"https://stackoverflow.com/users/6444776/ommadawn","reputation":2552,"display_name":"Ommadawn","accept_rate":84},"content_license":"CC BY-SA 4.0","score":0,"post_id":69940918,"reply_to_user":{"profile_image":"https://www.gravatar.com/avatar/aca8027396aa8e114f0a23a15f2d5b2e?s=256&d=identicon&r=PG","account_id":3068754,"user_type":"registered","user_id":2599899,"link":"https://stackoverflow.com/users/2599899/arthur-klezovich","reputation":2677,"display_name":"Arthur Klezovich"},"edited":false,"creation_date":1636711503,"comment_id":123634805,"body":"@ArthurKlezovich, no propagation type is configured :O"},{"owner":{"profile_image":"https://i.stack.imgur.com/shfxy.jpg?s=256&g=1","account_id":8604130,"user_type":"registered","user_id":6444776,"link":"https://stackoverflow.com/users/6444776/ommadawn","reputation":2552,"display_name":"Ommadawn","accept_rate":84},"content_license":"CC BY-SA 4.0","score":0,"post_id":69940918,"reply_to_user":{"profile_image":"https://www.gravatar.com/avatar/aca8027396aa8e114f0a23a15f2d5b2e?s=256&d=identicon&r=PG","account_id":3068754,"user_type":"registered","user_id":2599899,"link":"https://stackoverflow.com/users/2599899/arthur-klezovich","reputation":2677,"display_name":"Arthur Klezovich"},"edited":false,"creation_date":1636711233,"comment_id":123634703,"body":"@ArthurKlezovich, here is the stack trace log"},{"owner":{"profile_image":"https://www.gravatar.com/avatar/aca8027396aa8e114f0a23a15f2d5b2e?s=256&d=identicon&r=PG","account_id":3068754,"user_type":"registered","user_id":2599899,"link":"https://stackoverflow.com/users/2599899/arthur-klezovich","reputation":2677,"display_name":"Arthur Klezovich"},"content_license":"CC BY-SA 4.0","score":1,"post_id":69940918,"edited":false,"creation_date":1636711089,"comment_id":123634654,"body":"I think the problem is caused by the fact that your transactional method is called somewhere from another transactional method. Now then the what&#39;s the <a href=\"https://www.baeldung.com/spring-transactional-propagation-isolation\" rel=\"nofollow noreferrer\">transaction propagation type</a> you have configured in your system ?"},{"owner":{"profile_image":"https://www.gravatar.com/avatar/aca8027396aa8e114f0a23a15f2d5b2e?s=256&d=identicon&r=PG","account_id":3068754,"user_type":"registered","user_id":2599899,"link":"https://stackoverflow.com/users/2599899/arthur-klezovich","reputation":2677,"display_name":"Arthur Klezovich"},"content_license":"CC BY-SA 4.0","score":0,"post_id":69940918,"edited":false,"creation_date":1636711012,"comment_id":123634628,"body":"Which framework are you using ?"},{"owner":{"profile_image":"https://i.stack.imgur.com/shfxy.jpg?s=256&g=1","account_id":8604130,"user_type":"registered","user_id":6444776,"link":"https://stackoverflow.com/users/6444776/ommadawn","reputation":2552,"display_name":"Ommadawn","accept_rate":84},"content_license":"CC BY-SA 4.0","score":0,"post_id":69940918,"reply_to_user":{"profile_image":"https://www.gravatar.com/avatar/aca8027396aa8e114f0a23a15f2d5b2e?s=256&d=identicon&r=PG","account_id":3068754,"user_type":"registered","user_id":2599899,"link":"https://stackoverflow.com/users/2599899/arthur-klezovich","reputation":2677,"display_name":"Arthur Klezovich"},"edited":false,"creation_date":1636710990,"comment_id":123634618,"body":"@ArthurKlezovich, no, I&#39;m not using that annotation at all. Where should I use it? In the caller? In the method getById?"},{"owner":{"profile_image":"https://www.gravatar.com/avatar/aca8027396aa8e114f0a23a15f2d5b2e?s=256&d=identicon&r=PG","account_id":3068754,"user_type":"registered","user_id":2599899,"link":"https://stackoverflow.com/users/2599899/arthur-klezovich","reputation":2677,"display_name":"Arthur Klezovich"},"content_license":"CC BY-SA 4.0","score":0,"post_id":69940918,"edited":false,"creation_date":1636710797,"comment_id":123634553,"body":"Can you post the stack trace ?"},{"owner":{"profile_image":"https://www.gravatar.com/avatar/aca8027396aa8e114f0a23a15f2d5b2e?s=256&d=identicon&r=PG","account_id":3068754,"user_type":"registered","user_id":2599899,"link":"https://stackoverflow.com/users/2599899/arthur-klezovich","reputation":2677,"display_name":"Arthur Klezovich"},"content_license":"CC BY-SA 4.0","score":1,"post_id":69940918,"edited":false,"creation_date":1636710782,"comment_id":123634545,"body":"Are you using @Transactional annotation anywhere in the code base ?"},{"owner":{"profile_image":"https://lh5.googleusercontent.com/-cm-tuL0Mjvw/AAAAAAAAAAI/AAAAAAAAATw/hihlo0AbAoY/photo.jpg?sz=256","account_id":11179248,"user_type":"registered","user_id":8203759,"link":"https://stackoverflow.com/users/8203759/konstantin-annikov","reputation":11910,"display_name":"Konstantin Annikov"},"content_license":"CC BY-SA 4.0","score":0,"post_id":69935845,"edited":false,"creation_date":1636699871,"comment_id":123631099,"body":"To make sure IDE added all needed dependencies, you can open the .jar file as an archive and check inside.  Please post your project structure screenshot."},{"owner":{"profile_image":"https://lh4.googleusercontent.com/-XO5pmVBQa3Y/AAAAAAAAAAI/AAAAAAAAAAA/AMZuucnEnwT2r9D_vvE0tEkG_cwkXTZaXg/photo.jpg?sz=256","account_id":18554741,"user_type":"registered","user_id":13520144,"link":"https://stackoverflow.com/users/13520144/brunner-arthur","reputation":1,"display_name":"Brunner Arthur"},"content_license":"CC BY-SA 4.0","score":0,"post_id":69935845,"reply_to_user":{"profile_image":"https://i.stack.imgur.com/Rzz8Q.jpg?s=256&g=1","account_id":20240228,"user_type":"registered","user_id":14844306,"link":"https://stackoverflow.com/users/14844306/ben-anderson","reputation":496,"display_name":"Ben Anderson"},"edited":false,"creation_date":1636687660,"comment_id":123629010,"body":"These are the dependencies that appear under &#39;external libraries&#39; in my project and also the dependencies that appear when creating the artifact   : com.lowagie.text-2.1.7 commons-collections-3.2.1-1.0.0 commons-digester-2.1 commons-logging-1.1.1 itextpdf-5.5.1 jasperreports-5.0.1 org.apache.commons.beanutils poi-5.0"},{"owner":{"profile_image":"https://lh4.googleusercontent.com/-XO5pmVBQa3Y/AAAAAAAAAAI/AAAAAAAAAAA/AMZuucnEnwT2r9D_vvE0tEkG_cwkXTZaXg/photo.jpg?sz=256","account_id":18554741,"user_type":"registered","user_id":13520144,"link":"https://stackoverflow.com/users/13520144/brunner-arthur","reputation":1,"display_name":"Brunner Arthur"},"content_license":"CC BY-SA 4.0","score":0,"post_id":69935845,"reply_to_user":{"profile_image":"https://i.stack.imgur.com/Rzz8Q.jpg?s=256&g=1","account_id":20240228,"user_type":"registered","user_id":14844306,"link":"https://stackoverflow.com/users/14844306/ben-anderson","reputation":496,"display_name":"Ben Anderson"},"edited":false,"creation_date":1636687474,"comment_id":123628979,"body":"Is there another way of building the jar? And how do I verify that dependencies are  being built in the final jar file? Thanks."},{"owner":{"profile_image":"https://lh4.googleusercontent.com/-XO5pmVBQa3Y/AAAAAAAAAAI/AAAAAAAAAAA/AMZuucnEnwT2r9D_vvE0tEkG_cwkXTZaXg/photo.jpg?sz=256","account_id":18554741,"user_type":"registered","user_id":13520144,"link":"https://stackoverflow.com/users/13520144/brunner-arthur","reputation":1,"display_name":"Brunner Arthur"},"content_license":"CC BY-SA 4.0","score":0,"post_id":69935845,"reply_to_user":{"profile_image":"https://i.stack.imgur.com/Rzz8Q.jpg?s=256&g=1","account_id":20240228,"user_type":"registered","user_id":14844306,"link":"https://stackoverflow.com/users/14844306/ben-anderson","reputation":496,"display_name":"Ben Anderson"},"edited":false,"creation_date":1636687377,"comment_id":123628963,"body":"Ben,  The jar is built using the normal way intellij makes a jar. I just  go to project structure in intelllij and  try  to create a new  artifact. Then I count the dependencies to see if they are the same as  those in the tested project."},{"owner":{"profile_image":"https://i.stack.imgur.com/Rzz8Q.jpg?s=256&g=1","account_id":20240228,"user_type":"registered","user_id":14844306,"link":"https://stackoverflow.com/users/14844306/ben-anderson","reputation":496,"display_name":"Ben Anderson"},"content_license":"CC BY-SA 4.0","score":0,"post_id":69935845,"edited":false,"creation_date":1636671349,"comment_id":123626298,"body":"Make sure your dependencies are built into the final jar. What are you using to build the jar?"},{"owner":{"profile_image":"https://i.stack.imgur.com/RKSgV.png?s=256&g=1","account_id":2485939,"user_type":"registered","user_id":2164365,"link":"https://stackoverflow.com/users/2164365/abra","reputation":19426,"display_name":"Abra","accept_rate":40},"content_license":"CC BY-SA 4.0","score":1,"post_id":69923637,"edited":false,"creation_date":1636611914,"comment_id":123604969,"body":"<code>p2.size()</code> returns a number that is bigger than <code>t1.getPlayerList().size()</code>. I guess you probably think that they are the same size but it appears that they are not. You need to debug your code and try to discover why the sizes are different. If you need help debugging your code then I suggest that you <a href=\"https://stackoverflow.com/posts/69923637/edit\">edit</a> your question and post a <a href=\"https://stackoverflow.com/help/minimal-reproducible-example\">minimal reproducible example</a>. Note that you should <b>not</b> post all your code. Just post the minimal amount of code that causes the <code>IndexOutOfBoundsException</code>."},{"owner":{"profile_image":"https://i.stack.imgur.com/enNdg.jpg?s=256&g=1","account_id":21994,"user_type":"registered","user_id":53897,"link":"https://stackoverflow.com/users/53897/thorbj%c3%b8rn-ravn-andersen","reputation":73808,"display_name":"Thorbj&#248;rn Ravn Andersen","accept_rate":56},"content_license":"CC BY-SA 4.0","score":0,"post_id":69923637,"edited":false,"creation_date":1636609813,"comment_id":123604541,"body":"The arraylist is not as big as you expect it to be."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/e442a53d36f9351aee11b5ecb8369691?s=256&d=identicon&r=PG","account_id":6520,"user_type":"registered","user_id":11002,"link":"https://stackoverflow.com/users/11002/tgdavies","reputation":10523,"display_name":"tgdavies","accept_rate":75},"content_license":"CC BY-SA 4.0","score":5,"post_id":69923637,"edited":false,"creation_date":1636609339,"comment_id":123604465,"body":"What do you understand that exception to mean?"},{"owner":{"profile_image":"https://www.gravatar.com/avatar/72baa38005eb8de126b2dd2e6fa1d660?s=256&d=identicon&r=PG","account_id":319873,"user_type":"registered","user_id":637853,"link":"https://stackoverflow.com/users/637853/thomas","reputation":87612,"display_name":"Thomas","accept_rate":50},"content_license":"CC BY-SA 4.0","score":0,"post_id":67412378,"edited":false,"creation_date":1620285479,"comment_id":119156587,"body":"If you want to catch the exception do a <code>catch(NoSuchElementException)</code>. If you want to fix the error in the first place we might need some more info e.g. what the input was."},{"owner":{"profile_image":"https://graph.facebook.com/10159420994469363/picture?type=large","account_id":19934003,"user_type":"registered","user_id":14607078,"link":"https://stackoverflow.com/users/14607078/tom-ronaldo","reputation":21,"display_name":"Tom Ronaldo"},"content_license":"CC BY-SA 4.0","score":0,"post_id":67412378,"reply_to_user":{"profile_image":"https://www.gravatar.com/avatar/72baa38005eb8de126b2dd2e6fa1d660?s=256&d=identicon&r=PG","account_id":319873,"user_type":"registered","user_id":637853,"link":"https://stackoverflow.com/users/637853/thomas","reputation":87612,"display_name":"Thomas","accept_rate":50},"edited":false,"creation_date":1620281299,"comment_id":119155138,"body":"@Thomas I adjusted to the <code>nextDouble()</code> which is the latest code I sent, still shows the same error just replace that. I have been on this for good 4 hours, any ideas how can I fix it?"},{"owner":{"profile_image":"https://www.gravatar.com/avatar/72baa38005eb8de126b2dd2e6fa1d660?s=256&d=identicon&r=PG","account_id":319873,"user_type":"registered","user_id":637853,"link":"https://stackoverflow.com/users/637853/thomas","reputation":87612,"display_name":"Thomas","accept_rate":50},"content_license":"CC BY-SA 4.0","score":2,"post_id":67412378,"edited":false,"creation_date":1620279472,"comment_id":119154667,"body":"The code you&#39;ve posted doesn&#39;t match your exception, i.e. the code contains <code>nextDouble()</code> in <code>deposit()</code> but the exception mentions <code>nextFloat()</code>. That seems to indicate the code you&#39;ve submitted is not your current version. Also not that albeit a <code>InputMismatchException</code> extends <code>NoSuchElementException</code> the catch-block will only catch that specific subclass and not any other <code>NoSuchElementException</code>. You&#39;re getting the base exception here so of course it won&#39;t be caught."},{"owner":{"user_type":"does_not_exist","display_name":"user15613889"},"content_license":"CC BY-SA 4.0","score":2,"post_id":67402595,"reply_to_user":{"profile_image":"https://i.stack.imgur.com/QZ0Cl.png?s=256&g=1","account_id":13798611,"user_type":"registered","user_id":9959152,"link":"https://stackoverflow.com/users/9959152/ryuzaki-l","reputation":37885,"display_name":"Ryuzaki L"},"edited":false,"creation_date":1620224969,"comment_id":119138228,"body":"@Deadpool the &#39;@SpringBootTest&#39; seems to have worked!"},{"owner":{"profile_image":"https://i.stack.imgur.com/Vrc33.png?s=256&g=1","account_id":10172101,"user_type":"registered","user_id":7512072,"link":"https://stackoverflow.com/users/7512072/henrique-mentz","reputation":115,"display_name":"Henrique Mentz"},"content_license":"CC BY-SA 4.0","score":0,"post_id":67402595,"edited":false,"creation_date":1620222859,"comment_id":119136986,"body":"In class ContactServiceImplTest try to change <code>@Autowired</code> for <code>@InjectMocks</code> and <code>@MockBean</code> for <code>@Mock</code>. You could try to use <code>@ExtendWith(MockitoExtension.class)</code> instead of <code>@ExtendWith(SpringExtension.class)</code>."},{"owner":{"profile_image":"https://i.stack.imgur.com/QZ0Cl.png?s=256&g=1","account_id":13798611,"user_type":"registered","user_id":9959152,"link":"https://stackoverflow.com/users/9959152/ryuzaki-l","reputation":37885,"display_name":"Ryuzaki L"},"content_license":"CC BY-SA 4.0","score":0,"post_id":67402595,"edited":false,"creation_date":1620222832,"comment_id":119136966,"body":"are you trying to do integration test ? i believe you should use <code>@SpringBootTest</code>"},{"owner":{"profile_image":"https://www.gravatar.com/avatar/3d7a3b83131982dd87c1a37ea2ef5415?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":14854758,"user_type":"registered","user_id":10727619,"link":"https://stackoverflow.com/users/10727619/gamingfelix","reputation":239,"display_name":"GamingFelix"},"content_license":"CC BY-SA 4.0","score":1,"post_id":67400314,"edited":false,"creation_date":1620214144,"comment_id":119132782,"body":"This is rather messy. I&#39;d suggest you try to narrow your problem down to just one or two lines of code that is the actual problem / exception."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/244db4008d7e5835f267f2712956c7ec?s=256&d=identicon&r=PG","account_id":1536755,"user_type":"registered","user_id":1432580,"link":"https://stackoverflow.com/users/1432580/daniel-cheng","reputation":840,"display_name":"Daniel Cheng"},"content_license":"CC BY-SA 4.0","score":0,"post_id":67387023,"edited":false,"creation_date":1620139835,"comment_id":119109344,"body":"Are you trying to test exception is thrown or test the handling of the exception?"},{"owner":{"profile_image":"https://www.gravatar.com/avatar/44c841338e1646af9a977f1fa0e23948?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":162699,"user_type":"registered","user_id":3788176,"link":"https://stackoverflow.com/users/3788176/andy-turner","reputation":138060,"display_name":"Andy Turner","accept_rate":54},"content_license":"CC BY-SA 4.0","score":1,"post_id":67371571,"edited":false,"creation_date":1620055659,"comment_id":119081993,"body":"You don&#39;t catch the exception in a loop, so, yes, it will terminate after the exception is caught."},{"owner":{"profile_image":"https://i.stack.imgur.com/AWsdT.png?s=256&g=1","account_id":60521,"user_type":"registered","user_id":180719,"link":"https://stackoverflow.com/users/180719/olivier-gr%c3%a9goire","reputation":34336,"display_name":"Olivier Gr&#233;goire","accept_rate":88},"content_license":"CC BY-SA 3.0","score":2,"post_id":46091211,"edited":false,"creation_date":1504774875,"comment_id":79145896,"body":"Others tell you to fix your NPE. I&#39;ll tell you why: an NPE is a programmer&#39;s logic error, meaning that <i>you</i> made an error in what you think is correct. So, no, it&#39;s never okay to leave it as is. Hence people telling you to fix your NPE."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/02246f35e9f5c91a9d99a08b378e686c?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":3931956,"user_type":"registered","user_id":3250086,"link":"https://stackoverflow.com/users/3250086/garyf","reputation":521,"display_name":"garyF"},"content_license":"CC BY-SA 3.0","score":0,"post_id":46091211,"reply_to_user":{"profile_image":"https://i.stack.imgur.com/Xlzqs.png?s=256&g=1","account_id":8766622,"user_type":"registered","user_id":6554747,"link":"https://stackoverflow.com/users/6554747/progyammer","reputation":1498,"display_name":"progyammer","accept_rate":100},"edited":false,"creation_date":1504772509,"comment_id":79144355,"body":"@progyammer Not the statement. The ParentClass method will throw the exception in runtime. Actually, i don&#39;t need use that variable anymore in my subclass, but it&#39;s used in other subclasses of ParentClass."},{"owner":{"profile_image":"https://i.stack.imgur.com/Xlzqs.png?s=256&g=1","account_id":8766622,"user_type":"registered","user_id":6554747,"link":"https://stackoverflow.com/users/6554747/progyammer","reputation":1498,"display_name":"progyammer","accept_rate":100},"content_license":"CC BY-SA 3.0","score":0,"post_id":46091211,"edited":false,"creation_date":1504772376,"comment_id":79144273,"body":"You are including the statement, which can throw an error, inside a try-catch block, right?"},{"owner":{"profile_image":"https://www.gravatar.com/avatar/44c841338e1646af9a977f1fa0e23948?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":162699,"user_type":"registered","user_id":3788176,"link":"https://stackoverflow.com/users/3788176/andy-turner","reputation":138060,"display_name":"Andy Turner","accept_rate":54},"content_license":"CC BY-SA 3.0","score":3,"post_id":46091211,"edited":false,"creation_date":1504772189,"comment_id":79144160,"body":"&quot;But due to a different instantiation in SubClass, this problem may arise.&quot; Fix the different instantiation in <code>SubClass</code>."},{"owner":{"profile_image":"https://i.stack.imgur.com/hNkgF.png?s=256&g=1","account_id":4819600,"user_type":"registered","user_id":3890632,"link":"https://stackoverflow.com/users/3890632/khelwood","reputation":56510,"display_name":"khelwood"},"content_license":"CC BY-SA 3.0","score":1,"post_id":46091211,"edited":false,"creation_date":1504772027,"comment_id":79144061,"body":"You should generally fix NPEs rather than catching them."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/90b65fc5fb7ab727d1f770206d6b5325?s=256&d=identicon&r=PG","account_id":6306175,"user_type":"registered","user_id":4899193,"link":"https://stackoverflow.com/users/4899193/usagi-miyamoto","reputation":6201,"display_name":"Usagi Miyamoto"},"content_license":"CC BY-SA 3.0","score":5,"post_id":46091211,"edited":false,"creation_date":1504771992,"comment_id":79144037,"body":"You cannot. Try solving the NPE,instead..."},{"owner":{"profile_image":"https://i.stack.imgur.com/fl1Jg.jpg?s=256&g=1","account_id":557322,"user_type":"registered","user_id":919710,"link":"https://stackoverflow.com/users/919710/alexandre-santos","reputation":8250,"display_name":"Alexandre Santos","accept_rate":80},"content_license":"CC BY-SA 3.0","score":1,"post_id":23625440,"edited":false,"creation_date":1399970606,"comment_id":36276367,"body":"This might help clarify why you should not use exceptions to control flow: <a href=\"http://stackoverflow.com/questions/729379/why-not-use-exceptions-as-regular-flow-of-control\" title=\"why not use exceptions as regular flow of control\">stackoverflow.com/questions/729379/&hellip;</a>"},{"owner":{"profile_image":"https://www.gravatar.com/avatar/9420b13f41ea0c28b268d819209069a9?s=256&d=identicon&r=PG","account_id":13508,"user_type":"registered","user_id":27198,"link":"https://stackoverflow.com/users/27198/itay-maman","reputation":30357,"display_name":"Itay Maman","accept_rate":72},"content_license":"CC BY-SA 3.0","score":0,"post_id":23625440,"edited":false,"creation_date":1399969146,"comment_id":36275513,"body":"You&#39;re right they are related to some extent. My answer (below) focuses mainly on collecting the results from a hierarchy of checks."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/898acf6a15db4c6a250cb5036e27651a?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":2712204,"user_type":"registered","user_id":2340399,"link":"https://stackoverflow.com/users/2340399/maczikasz","reputation":1123,"display_name":"maczikasz"},"content_license":"CC BY-SA 3.0","score":0,"post_id":23625440,"edited":false,"creation_date":1399967999,"comment_id":36274864,"body":"take a look at this you might find it interesting: <a href=\"http://stackoverflow.com/questions/18314609/which-design-pattern-to-use-for-validation\" title=\"which design pattern to use for validation\">stackoverflow.com/questions/18314609/&hellip;</a>"},{"owner":{"profile_image":"https://i.stack.imgur.com/TaCMM.jpg?s=256&g=1","account_id":1242916,"user_type":"registered","user_id":1205066,"link":"https://stackoverflow.com/users/1205066/sergey","reputation":437,"display_name":"Sergey","accept_rate":100},"content_license":"CC BY-SA 3.0","score":0,"post_id":23625440,"reply_to_user":{"profile_image":"https://www.gravatar.com/avatar/9420b13f41ea0c28b268d819209069a9?s=256&d=identicon&r=PG","account_id":13508,"user_type":"registered","user_id":27198,"link":"https://stackoverflow.com/users/27198/itay-maman","reputation":30357,"display_name":"Itay Maman","accept_rate":72},"edited":false,"creation_date":1399967850,"comment_id":36274776,"body":"Both are equally important to me now. I suspect, that (b) influences the choice for (a) in some degree. Let us start with (b)."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/9420b13f41ea0c28b268d819209069a9?s=256&d=identicon&r=PG","account_id":13508,"user_type":"registered","user_id":27198,"link":"https://stackoverflow.com/users/27198/itay-maman","reputation":30357,"display_name":"Itay Maman","accept_rate":72},"content_license":"CC BY-SA 3.0","score":0,"post_id":23625440,"edited":false,"creation_date":1399967633,"comment_id":36274667,"body":"there are two directions where this question may be going: (a) how to build arrange the code that implements the check; (b) how to arrange the code that aggregates the failures reported by these checks. Which direction is your question about?"},{"owner":{"profile_image":"https://www.gravatar.com/avatar/dab08478b226280d4a30894c9a7ed719?s=256&d=identicon&r=PG","account_id":262968,"user_type":"registered","user_id":548225,"link":"https://stackoverflow.com/users/548225/anubhava","reputation":767170,"display_name":"anubhava","accept_rate":90},"content_license":"CC BY-SA 3.0","score":3,"post_id":8895091,"edited":false,"creation_date":1326805824,"comment_id":11122704,"body":"Even java.lang.Exception (<a href=\"http://docs.oracle.com/javase/1.5.0/docs/api/java/lang/Exception.html\" rel=\"nofollow noreferrer\">docs.oracle.com/javase/1.5.0/docs/api/java/lang/Exception.h&zwnj;&#8203;tml</a>) has a constructor with a String."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/d787caaf04b85641692a24099fcee990?s=256&d=identicon&r=PG","account_id":1885,"user_type":"registered","user_id":2598,"link":"https://stackoverflow.com/users/2598/jjnguy","reputation":137382,"display_name":"jjnguy","accept_rate":93},"content_license":"CC BY-SA 2.5","score":0,"post_id":1070590,"edited":false,"creation_date":1246480429,"comment_id":883833,"body":"The error you are getting leads me to believe that you are not correctly extending Exception."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/49f3a2065659f5b4efa05ae29bd0856a?s=256&d=identicon&r=PG","account_id":7745,"user_type":"moderator","user_id":13531,"link":"https://stackoverflow.com/users/13531/michael-myers","reputation":189775,"display_name":"Michael Myers","accept_rate":75},"content_license":"CC BY-SA 2.5","score":1,"post_id":1070590,"edited":false,"creation_date":1246480070,"comment_id":883802,"body":"Did you declare it as &quot;throws InvalidBankFeeAmountException&quot;?"},{"owner":{"profile_image":"https://www.gravatar.com/avatar/e6d1d662f2b3873887e61dafbed6d2c1?s=256&d=identicon&r=PG","account_id":42657,"user_type":"registered","user_id":124339,"link":"https://stackoverflow.com/users/124339/johanna","reputation":27146,"display_name":"Johanna","accept_rate":46},"content_license":"CC BY-SA 2.5","score":0,"post_id":1070590,"edited":false,"creation_date":1246478639,"comment_id":883679,"body":"but when I use this class as a type in the main() method the other warning will be shown that:Can not throw the type InvalidBankFeeAmountException."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/d787caaf04b85641692a24099fcee990?s=256&d=identicon&r=PG","account_id":1885,"user_type":"registered","user_id":2598,"link":"https://stackoverflow.com/users/2598/jjnguy","reputation":137382,"display_name":"jjnguy","accept_rate":93},"content_license":"CC BY-SA 2.5","score":1,"post_id":1070590,"edited":false,"creation_date":1246478482,"comment_id":883661,"body":"You don&#39;t have to worry about that warning if you don&#39;t want to.  Because the Exception class is serializable it requires you to set a serial id for the class.  But, since it is just a warning, I usually ignore it."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/e6d1d662f2b3873887e61dafbed6d2c1?s=256&d=identicon&r=PG","account_id":42657,"user_type":"registered","user_id":124339,"link":"https://stackoverflow.com/users/124339/johanna","reputation":27146,"display_name":"Johanna","accept_rate":46},"content_license":"CC BY-SA 2.5","score":0,"post_id":1070590,"edited":false,"creation_date":1246478238,"comment_id":883643,"body":"I created one Exception by myself which is shown above.create a class with the name of that special exception and extends Exception. BUT it has warning which is:The serializable class &lt;name of that Exception&gt;Exception does not declare a static final serialVersionUID field of long. How can I solve it?????"},{"owner":{"profile_image":"https://www.gravatar.com/avatar/fd2bfef83bc07bfe03aeb5f0ef08dc03?s=256&d=identicon&r=PG","account_id":1322512,"user_type":"registered","user_id":1268003,"link":"https://stackoverflow.com/users/1268003/martin-andersson","reputation":18477,"display_name":"Martin Andersson","accept_rate":82},"content_license":"CC BY-SA 4.0","score":0,"post_id":72600379,"edited":false,"creation_date":1675225320,"comment_id":132880803,"body":"Well then, isn&#39;t it <code>@param</code> that repeats <code>@throws</code>? (not giving Oracle-recommended order any relevance). Even if &quot;not null&quot; would be repeated I don&#39;t see the problem with that. In fact, I would be confused if <code>@param</code> states &quot;not null&quot; but I see no NPE listed in the <code>@throws</code> clause; which one is right, which one is up-to-date? The argument that an exception should not be documented because it is unchecked I wholeheartedly disagree with. We document for humans, not machines."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/d448323612608b991d0941b1376b98a0?s=256&d=identicon&r=PG","account_id":23968828,"user_type":"registered","user_id":17957852,"link":"https://stackoverflow.com/users/17957852/debanjan","reputation":104,"display_name":"Debanjan"},"content_license":"CC BY-SA 4.0","score":0,"post_id":72595248,"reply_to_user":{"profile_image":"https://www.gravatar.com/avatar/4d14bb9e5c27d2d26f8f6f011cc4571a?s=256&d=identicon&r=PG","account_id":1442354,"user_type":"registered","user_id":1362082,"link":"https://stackoverflow.com/users/1362082/franz","reputation":1913,"display_name":"Franz","accept_rate":53},"edited":false,"creation_date":1655063783,"comment_id":128236088,"body":"Go to your <code>UndefinedSubroutineException</code> class and change it to  <code>public class UndefinedSubroutineException extends RuntimeException</code>.   You do not need to change anything else in your code. Inside the test case <code>catch (UndefinedSubroutineException e)</code> block, you can now just write the logic of what you want to do if the Exception is caught."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/4d14bb9e5c27d2d26f8f6f011cc4571a?s=256&d=identicon&r=PG","account_id":1442354,"user_type":"registered","user_id":1362082,"link":"https://stackoverflow.com/users/1362082/franz","reputation":1913,"display_name":"Franz","accept_rate":53},"content_license":"CC BY-SA 4.0","score":0,"post_id":72595248,"edited":false,"creation_date":1655063173,"comment_id":128235975,"body":"how to rework UndefinedSubroutineException code , can you please advise ? testcase code II#m not allowed  change"},{"owner":{"profile_image":"https://i.stack.imgur.com/Mus1i.jpg?s=256&g=1","account_id":15975481,"user_type":"registered","user_id":11528511,"link":"https://stackoverflow.com/users/11528511/afzal-ali","reputation":910,"display_name":"Afzal Ali"},"content_license":"CC BY-SA 4.0","score":0,"post_id":72553074,"edited":false,"creation_date":1654761192,"comment_id":128170105,"body":"try catch is not a good approach in simple scenarios. If you are not sure about type of input. then just take it as string by Scanner.next0 and then convert it or check type before converting and prompt again if it is not required"},{"owner":{"profile_image":"https://i.stack.imgur.com/K1mTV.jpg?s=256&g=1","account_id":969721,"user_type":"registered","user_id":992484,"link":"https://stackoverflow.com/users/992484/madprogrammer","reputation":344527,"display_name":"MadProgrammer","accept_rate":60},"content_license":"CC BY-SA 4.0","score":1,"post_id":72553074,"edited":false,"creation_date":1654729497,"comment_id":128164255,"body":"Actually, I would suggest that <code>Scanner#hasNextInt</code> is a better approach, as you should not be using <code>try-catch</code> as a flow control mechanism (where possible).  Although to be honest, I&#39;d be tempted to just read the next token as a <code>String</code> and convert it manually, but that&#39;s me"},{"owner":{"profile_image":"https://www.gravatar.com/avatar/28d7fc76db803c6757e7cfd2cde20354?s=256&d=identicon&r=PG","account_id":31293,"user_type":"registered","user_id":85821,"link":"https://stackoverflow.com/users/85821/bart-van-heukelom","reputation":43494,"display_name":"Bart van Heukelom","accept_rate":73},"content_license":"CC BY-SA 4.0","score":0,"post_id":72547009,"edited":false,"creation_date":1654697867,"comment_id":128153606,"body":"An OutOfMemoryError does not necessarily leave memory usage high. If it&#39;s thrown because somebody is trying to upload a 1 TB file, usage should be back to normal afterwards. Of course, restarting a service if the memory usage is too high is indeed a good idea (stuff leaks), but requires different tools, e.g. monitoring heap usage over a longer time period."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/28d7fc76db803c6757e7cfd2cde20354?s=256&d=identicon&r=PG","account_id":31293,"user_type":"registered","user_id":85821,"link":"https://stackoverflow.com/users/85821/bart-van-heukelom","reputation":43494,"display_name":"Bart van Heukelom","accept_rate":73},"content_license":"CC BY-SA 4.0","score":0,"post_id":72547035,"edited":false,"creation_date":1654697416,"comment_id":128153392,"body":"&quot;your only remaining option is to toss your computer out the window and go live with the amish.&quot; - please post that as answer so I can accept it! Jokes aside, the piece I was missing is &quot;leaves e.g. a file handle half-open&quot;, so thanks. In that case, I admit defeat and shall endeavour to stop catching OOMs. Unfortunate that the same exception class is used for both stuff like that and for the failed allocation of a huge array, but at least now I know I may manually put a catch around all of the latter to throw an <code>InsufficientMemoryException</code> instead."},{"owner":{"profile_image":"https://i.stack.imgur.com/kJ1gZ.png?s=256&g=1","account_id":12954074,"user_type":"registered","user_id":9365478,"link":"https://stackoverflow.com/users/9365478/martosfre","reputation":804,"display_name":"martosfre"},"content_license":"CC BY-SA 4.0","score":0,"post_id":69945846,"edited":false,"creation_date":1652977337,"comment_id":127744007,"body":"The problem is not the IDE, the problem is because the jasper version is different between the maven library and jasper studio used to compile the report."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/aca8027396aa8e114f0a23a15f2d5b2e?s=256&d=identicon&r=PG","account_id":3068754,"user_type":"registered","user_id":2599899,"link":"https://stackoverflow.com/users/2599899/arthur-klezovich","reputation":2677,"display_name":"Arthur Klezovich"},"content_license":"CC BY-SA 4.0","score":0,"post_id":70008144,"reply_to_user":{"profile_image":"https://www.gravatar.com/avatar/f7cf53bd8e67338b36d086f48477edfa?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":22531657,"user_type":"registered","user_id":16723586,"link":"https://stackoverflow.com/users/16723586/kiznet007","reputation":15,"display_name":"Kiznet007"},"edited":false,"creation_date":1637312749,"comment_id":123797968,"body":"@Kiznet007 Any time, bro ;)"},{"owner":{"profile_image":"https://www.gravatar.com/avatar/f7cf53bd8e67338b36d086f48477edfa?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":22531657,"user_type":"registered","user_id":16723586,"link":"https://stackoverflow.com/users/16723586/kiznet007","reputation":15,"display_name":"Kiznet007"},"content_license":"CC BY-SA 4.0","score":0,"post_id":70008144,"edited":false,"creation_date":1637252935,"comment_id":123782370,"body":"@ArthurKlezovich You&#39;re absolutely right! Thank you for bringing that up."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/aca8027396aa8e114f0a23a15f2d5b2e?s=256&d=identicon&r=PG","account_id":3068754,"user_type":"registered","user_id":2599899,"link":"https://stackoverflow.com/users/2599899/arthur-klezovich","reputation":2677,"display_name":"Arthur Klezovich"},"content_license":"CC BY-SA 4.0","score":0,"post_id":70008144,"reply_to_user":{"profile_image":"https://www.gravatar.com/avatar/f7cf53bd8e67338b36d086f48477edfa?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":22531657,"user_type":"registered","user_id":16723586,"link":"https://stackoverflow.com/users/16723586/kiznet007","reputation":15,"display_name":"Kiznet007"},"edited":false,"creation_date":1637226659,"comment_id":123771011,"body":"@Kiznet007 You are just using a lower version. <a href=\"https://developers.redhat.com/blog/2018/05/25/simplify-local-variable-type-definition-using-the-java-10-var-keyword#:~:text=In%20Java%2010%2C%20the%20var,t%20need%20to%20declare%20that.&amp;text=Each%20statement%20containing%20the%20var,the%20declared%20type%20of%20value\" rel=\"nofollow noreferrer\">developers.redhat.com/blog/2018/05/25/&hellip;</a>."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/f7cf53bd8e67338b36d086f48477edfa?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":22531657,"user_type":"registered","user_id":16723586,"link":"https://stackoverflow.com/users/16723586/kiznet007","reputation":15,"display_name":"Kiznet007"},"content_license":"CC BY-SA 4.0","score":0,"post_id":70008150,"edited":false,"creation_date":1637199755,"comment_id":123765155,"body":"I didn&#39;t think it was appropriate for you to state that &quot;SO is not a handholding kind of forum&quot; to me. I&#39;m 2 months in to learning Java. So yeah I have a lot of questions and I&#39;m trying to fill the gap where I need help! But thank you for your assistance anyways it works."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/b13bedc5215730fbce5edff6c130988a?s=256&d=identicon&r=PG","account_id":401843,"user_type":"registered","user_id":768644,"link":"https://stackoverflow.com/users/768644/rzwitserloot","reputation":89873,"display_name":"rzwitserloot"},"content_license":"CC BY-SA 4.0","score":0,"post_id":70008150,"reply_to_user":{"profile_image":"https://www.gravatar.com/avatar/f7cf53bd8e67338b36d086f48477edfa?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":22531657,"user_type":"registered","user_id":16723586,"link":"https://stackoverflow.com/users/16723586/kiznet007","reputation":15,"display_name":"Kiznet007"},"edited":false,"creation_date":1637197032,"comment_id":123764666,"body":"I gave you the right answer, that&#39;s &#39;belittling&#39;? There are various resources available on-site about what SO is for."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/f7cf53bd8e67338b36d086f48477edfa?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":22531657,"user_type":"registered","user_id":16723586,"link":"https://stackoverflow.com/users/16723586/kiznet007","reputation":15,"display_name":"Kiznet007"},"content_license":"CC BY-SA 4.0","score":0,"post_id":70008150,"edited":false,"creation_date":1637194720,"comment_id":123764264,"body":"To my understanding SO is forum for people who want to learn and that need help when they come to a road block. The simple fact that you belittle peoples answers or questions is confusing to me. If that&#39;s what you&#39;re looking to do then SO isn&#39;t a forum for you!"},{"owner":{"profile_image":"https://www.gravatar.com/avatar/b13bedc5215730fbce5edff6c130988a?s=256&d=identicon&r=PG","account_id":401843,"user_type":"registered","user_id":768644,"link":"https://stackoverflow.com/users/768644/rzwitserloot","reputation":89873,"display_name":"rzwitserloot"},"content_license":"CC BY-SA 4.0","score":0,"post_id":70008150,"reply_to_user":{"profile_image":"https://www.gravatar.com/avatar/f7cf53bd8e67338b36d086f48477edfa?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":22531657,"user_type":"registered","user_id":16723586,"link":"https://stackoverflow.com/users/16723586/kiznet007","reputation":15,"display_name":"Kiznet007"},"edited":false,"creation_date":1637193316,"comment_id":123763976,"body":"You&#39;d just do <code>double a = askDouble(scanner, &quot;Enter the first number:&quot;);</code> - you do not want, or need, a separate variant of <code>askDouble</code> for each question you care to ask. Follow a basic java tutorial - SO is not a handholding kind of forum. I can&#39;t help you without a paste of the exact code you have and the error you have (and such a question probably isn&#39;t appropriate for SO)."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/f7cf53bd8e67338b36d086f48477edfa?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":22531657,"user_type":"registered","user_id":16723586,"link":"https://stackoverflow.com/users/16723586/kiznet007","reputation":15,"display_name":"Kiznet007"},"content_license":"CC BY-SA 4.0","score":0,"post_id":70008150,"edited":false,"creation_date":1637192707,"comment_id":123763867,"body":"This is something that works but I start having issues with my variables because each input was originally a variable on its own. I created separate methods for each variable but that doesn&#39;t work because the Scanner input parameter that I created in my smallest()method is using double. And I get compiler errors in my askDouble() method in my main class. I&#39;ve tried different things and just a little clarification. So need a little assistance. TYIA!"},{"owner":{"profile_image":"https://www.gravatar.com/avatar/f7cf53bd8e67338b36d086f48477edfa?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":22531657,"user_type":"registered","user_id":16723586,"link":"https://stackoverflow.com/users/16723586/kiznet007","reputation":15,"display_name":"Kiznet007"},"content_license":"CC BY-SA 4.0","score":0,"post_id":70008144,"edited":false,"creation_date":1637189652,"comment_id":123763250,"body":"Did you create this in JS? Because var isn&#39;t even a keyword for Java. Just curious.."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/aca8027396aa8e114f0a23a15f2d5b2e?s=256&d=identicon&r=PG","account_id":3068754,"user_type":"registered","user_id":2599899,"link":"https://stackoverflow.com/users/2599899/arthur-klezovich","reputation":2677,"display_name":"Arthur Klezovich"},"content_license":"CC BY-SA 4.0","score":0,"post_id":70008144,"reply_to_user":{"profile_image":"https://www.gravatar.com/avatar/b13bedc5215730fbce5edff6c130988a?s=256&d=identicon&r=PG","account_id":401843,"user_type":"registered","user_id":768644,"link":"https://stackoverflow.com/users/768644/rzwitserloot","reputation":89873,"display_name":"rzwitserloot"},"edited":false,"creation_date":1637166638,"comment_id":123754877,"body":"See this line &quot;Then you do manual parsing and validation and if everything is OK&quot;"},{"owner":{"profile_image":"https://www.gravatar.com/avatar/b13bedc5215730fbce5edff6c130988a?s=256&d=identicon&r=PG","account_id":401843,"user_type":"registered","user_id":768644,"link":"https://stackoverflow.com/users/768644/rzwitserloot","reputation":89873,"display_name":"rzwitserloot"},"content_license":"CC BY-SA 4.0","score":0,"post_id":70008144,"edited":false,"creation_date":1637166592,"comment_id":123754857,"body":"This does not, at all, solve the problem of re-asking for input if the provided input isn&#39;t properly formatted. Also, indicating that an answer solves a problem is done on SO by being accepted. Don&#39;t invent your own systems for handling the concept of &#39;hey that works&#39;."},{"owner":{"profile_image":"https://i.stack.imgur.com/shfxy.jpg?s=256&g=1","account_id":8604130,"user_type":"registered","user_id":6444776,"link":"https://stackoverflow.com/users/6444776/ommadawn","reputation":2552,"display_name":"Ommadawn","accept_rate":84},"content_license":"CC BY-SA 4.0","score":0,"post_id":69941125,"edited":false,"creation_date":1636967318,"comment_id":123689638,"body":"Thanks! I&#39;ve a lot of work to do. I&#39;ll take a look carefully to find the point"},{"owner":{"profile_image":"https://www.gravatar.com/avatar/f7cf53bd8e67338b36d086f48477edfa?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":22531657,"user_type":"registered","user_id":16723586,"link":"https://stackoverflow.com/users/16723586/kiznet007","reputation":15,"display_name":"Kiznet007"},"content_license":"CC BY-SA 4.0","score":0,"post_id":69893623,"edited":false,"creation_date":1636473413,"comment_id":123563771,"body":"Great! So this works how I want it to work to accept only words and throw an exception when the user enters only numbers. Note: with Patter pattern = Pattern.compile(&quot;-?[0-9]+.?[0-9]+&quot;) it doesn&#39;t throw an exception with single digits. So I modified the line with: Pattern pattern = Pattern.compile(&quot;-?[0-9]+&quot;); and now it works perfectly! Thank you @MakerStack!"},{"owner":{"profile_image":"https://i.stack.imgur.com/7o61L.jpg?s=256&g=1","account_id":3635110,"user_type":"registered","user_id":3030406,"link":"https://stackoverflow.com/users/3030406/rookie007","reputation":1239,"display_name":"Rookie007","accept_rate":55},"content_license":"CC BY-SA 4.0","score":0,"post_id":69893623,"edited":false,"creation_date":1636440039,"comment_id":123550323,"body":"Add some explanation,  to understand better."},{"owner":{"profile_image":"https://i.stack.imgur.com/RIZKi.png?s=256&g=1","account_id":24885,"user_type":"registered","user_id":63550,"link":"https://stackoverflow.com/users/63550/peter-mortensen","reputation":30829,"display_name":"Peter Mortensen","accept_rate":78},"content_license":"CC BY-SA 4.0","score":1,"post_id":39789268,"edited":false,"creation_date":1598921524,"comment_id":112607033,"body":"An explanation would be in order. Especially as it is very different from the other answers, it would be nice to see a justification for if it really answers the question. For example, what is the idea behind it?"},{"owner":{"profile_image":"https://www.gravatar.com/avatar/02246f35e9f5c91a9d99a08b378e686c?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":3931956,"user_type":"registered","user_id":3250086,"link":"https://stackoverflow.com/users/3250086/garyf","reputation":521,"display_name":"garyF"},"content_license":"CC BY-SA 3.0","score":0,"post_id":46091271,"edited":false,"creation_date":1504773030,"comment_id":79144681,"body":"Thanks! Looks like i need to &quot;hack&quot; my way around this limitation by creating dummy stuff and then overriding with actual stuff. <code>@Override void foo() { super.ref = new Object(); super.foo(); super.ref = null; this.ref.doSomething();}</code> I want it null because i want to be semantic in my code."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/113b0b46b3de42ce4dee28c6006a85c5?s=256&d=identicon&r=PG","account_id":63444,"user_type":"registered","user_id":187808,"link":"https://stackoverflow.com/users/187808/tamas-rev","reputation":7018,"display_name":"Tamas Rev","accept_rate":100},"content_license":"CC BY-SA 3.0","score":1,"post_id":46091396,"reply_to_user":{"profile_image":"https://www.gravatar.com/avatar/44c841338e1646af9a977f1fa0e23948?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":162699,"user_type":"registered","user_id":3788176,"link":"https://stackoverflow.com/users/3788176/andy-turner","reputation":138060,"display_name":"Andy Turner","accept_rate":54},"edited":false,"creation_date":1504772956,"comment_id":79144642,"body":"Right, updating the answer."},{"owner":{"profile_image":"https://i.stack.imgur.com/2dGPn.jpg?s=256&g=1","account_id":2766415,"user_type":"registered","user_id":2382032,"link":"https://stackoverflow.com/users/2382032/eric-scherrer","reputation":3338,"display_name":"Eric Scherrer","accept_rate":90},"content_license":"CC BY-SA 3.0","score":0,"post_id":2792746,"edited":false,"creation_date":1503712338,"comment_id":78741837,"body":"I think error codes are helpful, but they end up being a maintenance issue for proprietary internal corporate software when they do not get the pruning they need. For commercial software they are very helpful."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/88dc87a6d2adc2241fab16bd958f3a88?s=256&d=identicon&r=PG","account_id":1297352,"user_type":"registered","user_id":2439715,"link":"https://stackoverflow.com/users/2439715/abhishek-goel","reputation":19013,"display_name":"Abhishek Goel","accept_rate":76},"content_license":"CC BY-SA 3.0","score":0,"post_id":26659191,"reply_to_user":{"profile_image":"https://i.stack.imgur.com/5jQlF.jpg?s=256&g=1","account_id":85265,"user_type":"registered","user_id":237838,"link":"https://stackoverflow.com/users/237838/andrew-barber","reputation":39803,"display_name":"Andrew Barber","accept_rate":86},"edited":false,"creation_date":1414846606,"comment_id":41975884,"body":"@AndrewBarber can you tell me which answers tells to remove in.close(). I know I have not provided any explanation but the answer is right. Accepted answer tells to use only 1 scanner ( which sometimes is not possible ), I have said don&#39;t close the scanner at all. There is difference in both answers ( if you read carefully )."},{"owner":{"profile_image":"https://i.stack.imgur.com/5jQlF.jpg?s=256&g=1","account_id":85265,"user_type":"registered","user_id":237838,"link":"https://stackoverflow.com/users/237838/andrew-barber","reputation":39803,"display_name":"Andrew Barber","accept_rate":86},"content_license":"CC BY-SA 3.0","score":0,"post_id":26659191,"edited":false,"creation_date":1414815089,"comment_id":41970099,"body":"This answer was really already given, and with a much better explanation."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/88dc87a6d2adc2241fab16bd958f3a88?s=256&d=identicon&r=PG","account_id":1297352,"user_type":"registered","user_id":2439715,"link":"https://stackoverflow.com/users/2439715/abhishek-goel","reputation":19013,"display_name":"Abhishek Goel","accept_rate":76},"content_license":"CC BY-SA 3.0","score":0,"post_id":26659191,"edited":false,"creation_date":1414693749,"comment_id":41923301,"body":"I was also facing the same problem.. After searching a lot on internet and finally removing in.close() from my code worked for me. That&#39;s why I&#39;ve answered this."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/a86a311e34d94a802e8bf88e2807ede3?s=256&d=identicon&r=PG","account_id":25029,"user_type":"registered","user_id":64046,"link":"https://stackoverflow.com/users/64046/jasonmarcher","reputation":14407,"display_name":"JasonMArcher"},"content_license":"CC BY-SA 3.0","score":0,"post_id":26659191,"edited":false,"creation_date":1414693419,"comment_id":41923105,"body":"This duplicates the accepted answer, but at a much lower quality."},{"owner":{"profile_image":"https://i.stack.imgur.com/J56Tk.jpg?s=256&g=1","account_id":545654,"user_type":"registered","user_id":1360984,"link":"https://stackoverflow.com/users/1360984/harmlezz","reputation":7998,"display_name":"Harmlezz","accept_rate":60},"content_license":"CC BY-SA 3.0","score":0,"post_id":23625681,"edited":false,"creation_date":1399972478,"comment_id":36277645,"body":"If you do not like pass it in, then you have to return them. Either by throwing an exception containing all the rules violated or by returning a type which contains either the validated value or a collection of violations. It&#39;s up to you and your design how you like to treat the parsed / validated values, when you need them and how and when you want to address the violations / create the human readable messages."},{"owner":{"profile_image":"https://i.stack.imgur.com/TaCMM.jpg?s=256&g=1","account_id":1242916,"user_type":"registered","user_id":1205066,"link":"https://stackoverflow.com/users/1205066/sergey","reputation":437,"display_name":"Sergey","accept_rate":100},"content_license":"CC BY-SA 3.0","score":0,"post_id":23625681,"edited":false,"creation_date":1399971315,"comment_id":36276840,"body":"What I would like to avoid is passing here and there an object, containing violations.  <code>violations.addAll(AgeValidator.validate(&quot;0042&quot;)); violations.addAll(UrlValidator.validate(&quot;http:&#47;&#47;some.website&zwnj;&#8203;.com&quot;)); if(violations.NotEmpty) throw ExceptionFactory.newException(violations);</code>  looks much more clean to me."},{"owner":{"profile_image":"https://i.stack.imgur.com/fl1Jg.jpg?s=256&g=1","account_id":557322,"user_type":"registered","user_id":919710,"link":"https://stackoverflow.com/users/919710/alexandre-santos","reputation":8250,"display_name":"Alexandre Santos","accept_rate":80},"content_license":"CC BY-SA 3.0","score":0,"post_id":23625804,"reply_to_user":{"profile_image":"https://i.stack.imgur.com/TaCMM.jpg?s=256&g=1","account_id":1242916,"user_type":"registered","user_id":1205066,"link":"https://stackoverflow.com/users/1205066/sergey","reputation":437,"display_name":"Sergey","accept_rate":100},"edited":false,"creation_date":1399970242,"comment_id":36276134,"body":"Yep. Saw that. Unfortunately there are no best practices. Just scars from previous battles."},{"owner":{"profile_image":"https://i.stack.imgur.com/TaCMM.jpg?s=256&g=1","account_id":1242916,"user_type":"registered","user_id":1205066,"link":"https://stackoverflow.com/users/1205066/sergey","reputation":437,"display_name":"Sergey","accept_rate":100},"content_license":"CC BY-SA 3.0","score":0,"post_id":23625804,"edited":false,"creation_date":1399970150,"comment_id":36276078,"body":"The question was about general best practices, including situations, when one cannot use a framework. I do use <code>javax.validation</code> already, so some formal validation is already covered. Thank you for useful link, I will put it into original post."},{"owner":{"profile_image":"https://i.stack.imgur.com/TaCMM.jpg?s=256&g=1","account_id":1242916,"user_type":"registered","user_id":1205066,"link":"https://stackoverflow.com/users/1205066/sergey","reputation":437,"display_name":"Sergey","accept_rate":100},"content_license":"CC BY-SA 3.0","score":0,"post_id":23625868,"edited":false,"creation_date":1399969794,"comment_id":36275870,"body":"I would like to keep formal and logical checks apart, so I think of some constructor for <code>LogicalChecker</code>, which uses a list of formally valid fields (which I have previously validated with <code>FormalChecker</code>).  I guess this still fits your approach."},{"owner":{"profile_image":"https://i.stack.imgur.com/fl1Jg.jpg?s=256&g=1","account_id":557322,"user_type":"registered","user_id":919710,"link":"https://stackoverflow.com/users/919710/alexandre-santos","reputation":8250,"display_name":"Alexandre Santos","accept_rate":80},"content_license":"CC BY-SA 3.0","score":0,"post_id":23625681,"edited":false,"creation_date":1399968907,"comment_id":36275380,"body":"Could you paste some code where 2 exceptions are thrown at the same time?"},{"owner":{"profile_image":"https://i.stack.imgur.com/J56Tk.jpg?s=256&g=1","account_id":545654,"user_type":"registered","user_id":1360984,"link":"https://stackoverflow.com/users/1360984/harmlezz","reputation":7998,"display_name":"Harmlezz","accept_rate":60},"content_license":"CC BY-SA 3.0","score":0,"post_id":23625681,"reply_to_user":{"profile_image":"https://i.stack.imgur.com/fl1Jg.jpg?s=256&g=1","account_id":557322,"user_type":"registered","user_id":919710,"link":"https://stackoverflow.com/users/919710/alexandre-santos","reputation":8250,"display_name":"Alexandre Santos","accept_rate":80},"edited":false,"creation_date":1399968860,"comment_id":36275354,"body":"I think you are able and should throw two exceptions. Each validation rule should be processed individually. It could be the responsibility of the exception container to group related exceptions. I would not throw one exception wit sub-exceptions, because the requirement to merge those information is motivated by the view and not by the validation layer. Hence never provide logic at a layer where no need can be motivated. It will not become messy in my opinion. It becomes clean and well separated."},{"owner":{"profile_image":"https://i.stack.imgur.com/fl1Jg.jpg?s=256&g=1","account_id":557322,"user_type":"registered","user_id":919710,"link":"https://stackoverflow.com/users/919710/alexandre-santos","reputation":8250,"display_name":"Alexandre Santos","accept_rate":80},"content_license":"CC BY-SA 3.0","score":0,"post_id":23625868,"edited":false,"creation_date":1399968696,"comment_id":36275264,"body":"How would it handle different date parsers?"},{"owner":{"profile_image":"https://i.stack.imgur.com/fl1Jg.jpg?s=256&g=1","account_id":557322,"user_type":"registered","user_id":919710,"link":"https://stackoverflow.com/users/919710/alexandre-santos","reputation":8250,"display_name":"Alexandre Santos","accept_rate":80},"content_license":"CC BY-SA 3.0","score":0,"post_id":23625868,"edited":false,"creation_date":1399968659,"comment_id":36275238,"body":"Would Checker need all possible checks done in the system added to it?"},{"owner":{"profile_image":"https://i.stack.imgur.com/fl1Jg.jpg?s=256&g=1","account_id":557322,"user_type":"registered","user_id":919710,"link":"https://stackoverflow.com/users/919710/alexandre-santos","reputation":8250,"display_name":"Alexandre Santos","accept_rate":80},"content_license":"CC BY-SA 3.0","score":0,"post_id":23625681,"edited":false,"creation_date":1399968488,"comment_id":36275140,"body":"Well, there are many problem associated with this solution, which at the surface seems ok. One of such problems is consolidating many errors in the same exception. For example, suppose a field fails 2 validations (length and type for example), would you throw 2 exceptions (you couldn&#39;t). Then you have to throw one exception with a list of sub-exceptions. It gets messy really fast."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/d787caaf04b85641692a24099fcee990?s=256&d=identicon&r=PG","account_id":1885,"user_type":"registered","user_id":2598,"link":"https://stackoverflow.com/users/2598/jjnguy","reputation":137382,"display_name":"jjnguy","accept_rate":93},"content_license":"CC BY-SA 3.0","score":5,"post_id":1070593,"reply_to_user":{"profile_image":"https://www.gravatar.com/avatar/6de7362951ec5bf3d40fa02de7175552?s=256&d=identicon&r=PG","account_id":1077413,"user_type":"registered","user_id":1075247,"link":"https://stackoverflow.com/users/1075247/ancientswordrage","reputation":7308,"display_name":"AncientSwordRage","accept_rate":92},"edited":false,"creation_date":1365000385,"comment_id":22451515,"body":"@Pureferret I don&#39;t think it&#39;s bad practice to extend <code>RuntimeException</code>. It definitely makes your code easier to use if there aren&#39;t checked exceptions all over the place."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/6de7362951ec5bf3d40fa02de7175552?s=256&d=identicon&r=PG","account_id":1077413,"user_type":"registered","user_id":1075247,"link":"https://stackoverflow.com/users/1075247/ancientswordrage","reputation":7308,"display_name":"AncientSwordRage","accept_rate":92},"content_license":"CC BY-SA 3.0","score":0,"post_id":1070593,"edited":false,"creation_date":1364989815,"comment_id":22444209,"body":"I just read the rest of the answer, you&#39;ve got it covered, I just need to read more than the code before commenting."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/6de7362951ec5bf3d40fa02de7175552?s=256&d=identicon&r=PG","account_id":1077413,"user_type":"registered","user_id":1075247,"link":"https://stackoverflow.com/users/1075247/ancientswordrage","reputation":7308,"display_name":"AncientSwordRage","accept_rate":92},"content_license":"CC BY-SA 3.0","score":5,"post_id":1070593,"edited":false,"creation_date":1364989561,"comment_id":22444074,"body":"I&#39;ve heard it can be bad practice to extend <a href=\"http://docs.oracle.com/javase/tutorial/essential/exceptions/runtime.html\" rel=\"nofollow noreferrer\">RuntimeExceptions</a>: <i>If a client can reasonably be expected to recover from an exception, make it a checked exception. If a client cannot do anything to recover from the exception, make it an unchecked exception.</i>"},{"owner":{"profile_image":"https://www.gravatar.com/avatar/d172333ccceefbcc91c2f38bbd30b332?s=256&d=identicon&r=PG","account_id":2489985,"user_type":"registered","user_id":2167671,"link":"https://stackoverflow.com/users/2167671/isaac-smith","reputation":173,"display_name":"Isaac Smith"},"content_license":"CC BY-SA 3.0","score":1,"post_id":15398862,"edited":false,"creation_date":1363337347,"comment_id":21819424,"body":"Thanks to you and syb0rg. I just had to delete the method with the scanner in it and place the equivalent in the main method. It works! First success in a new programming language... feels really good. :)"},{"owner":{"profile_image":"https://www.gravatar.com/avatar/d172333ccceefbcc91c2f38bbd30b332?s=256&d=identicon&r=PG","account_id":2489985,"user_type":"registered","user_id":2167671,"link":"https://stackoverflow.com/users/2167671/isaac-smith","reputation":173,"display_name":"Isaac Smith"},"content_license":"CC BY-SA 3.0","score":0,"post_id":15398752,"edited":false,"creation_date":1363276901,"comment_id":21795158,"body":"Thank you! I wish I had enough points on here to upvote you. I fixed what you said, and it still didn&#39;t work... but the good news is, once I took the scanner out of the method, I was able to just put it all in the main method and it worked fine. Helped with number initializing too. Thanks again! :)"},{"owner":{"profile_image":"https://i.stack.imgur.com/XpiU6.jpg?s=256&g=1","account_id":2189891,"user_type":"registered","user_id":1937270,"link":"https://stackoverflow.com/users/1937270/syb0rg","reputation":8117,"display_name":"syb0rg","accept_rate":91},"content_license":"CC BY-SA 3.0","score":0,"post_id":15398862,"edited":false,"creation_date":1363221436,"comment_id":21770045,"body":"+1, I forgot to mention the multiple Scanners with one input problem."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/0382297f273df0a544b0c6c2734de096?s=256&d=identicon&r=PG","account_id":9193,"user_type":"registered","user_id":16883,"link":"https://stackoverflow.com/users/16883/michael-borgwardt","reputation":343123,"display_name":"Michael Borgwardt","accept_rate":83},"content_license":"CC BY-SA 2.5","score":0,"post_id":3625721,"edited":false,"creation_date":1283452475,"comment_id":3813800,"body":"@magggi: Um, no. The catch block handles the exception and the loop continues as if nothing had happened."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/2b39a4a337cd772a45c78706b173313d?s=256&d=identicon&r=PG","account_id":174942,"user_type":"registered","user_id":404608,"link":"https://stackoverflow.com/users/404608/magggi","reputation":1145,"display_name":"Magggi","accept_rate":14},"content_license":"CC BY-SA 2.5","score":0,"post_id":3625721,"edited":false,"creation_date":1283450176,"comment_id":3813461,"body":"You are correct.But with this logic the program would exit after logging the measage.  * But what if there are some more files remaining?  * I want to process the remaining files even after the exception.."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/0382297f273df0a544b0c6c2734de096?s=256&d=identicon&r=PG","account_id":9193,"user_type":"registered","user_id":16883,"link":"https://stackoverflow.com/users/16883/michael-borgwardt","reputation":343123,"display_name":"Michael Borgwardt","accept_rate":83},"content_license":"CC BY-SA 2.5","score":0,"post_id":3625721,"reply_to_user":{"profile_image":"https://www.gravatar.com/avatar/465fb55f784b092bd32a669c5923d72c?s=256&d=identicon&r=PG","account_id":69219,"user_type":"registered","user_id":201557,"link":"https://stackoverflow.com/users/201557/thierry","reputation":5340,"display_name":"Thierry"},"edited":false,"creation_date":1283427809,"comment_id":3809719,"body":"@Thierry: Stack traces are useful for solving bugs in the code; It sounded to me like the question was more about things like FileNotFoundException where the stack trace is not useful."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/465fb55f784b092bd32a669c5923d72c?s=256&d=identicon&r=PG","account_id":69219,"user_type":"registered","user_id":201557,"link":"https://stackoverflow.com/users/201557/thierry","reputation":5340,"display_name":"Thierry"},"content_license":"CC BY-SA 2.5","score":0,"post_id":3625721,"edited":false,"creation_date":1283424940,"comment_id":3809287,"body":"Is there a reason for not logging the stacktrace ? I find the exception message is often not enough to understand a problem and reproduce it."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/906c0f71ce59f957527d739e9622c612?s=256&d=identicon&r=PG","account_id":24075,"user_type":"registered","user_id":60956,"link":"https://stackoverflow.com/users/60956/joel","reputation":29658,"display_name":"Joel","accept_rate":85},"content_license":"CC BY-SA 2.5","score":2,"post_id":3625721,"edited":false,"creation_date":1283420151,"comment_id":3808652,"body":"Although in practice, if you are opening a connection to the file, you will want to add a finally block in which to close the connection as per Colins answer."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/9ca9e0c0bf07d39f1c29776e766ba4cc?s=256&d=identicon&r=PG","account_id":8396,"user_type":"registered","user_id":15108,"link":"https://stackoverflow.com/users/15108/boutta","reputation":24329,"display_name":"boutta","accept_rate":89},"content_license":"CC BY-SA 2.5","score":1,"post_id":3625721,"edited":false,"creation_date":1283420053,"comment_id":3808638,"body":"It may be better style to not catch the general Exception type but rather specific exception types (IOException,...)."},{"owner":{"profile_image":"https://i.stack.imgur.com/5DblQ.png?s=256&g=1","account_id":8326,"user_type":"registered","user_id":14955,"link":"https://stackoverflow.com/users/14955/thilo","reputation":258555,"display_name":"Thilo","accept_rate":55},"content_license":"CC BY-SA 2.5","score":1,"post_id":3625721,"edited":false,"creation_date":1283420044,"comment_id":3808635,"body":"+1 for the meaningful log message (including the file name). Most code I see has just <code>logger.info(e.getMessage())</code>."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/28d048fac5e3ee385b01370382a6e987?s=256&d=identicon&r=PG","account_id":185700,"user_type":"registered","user_id":422597,"link":"https://stackoverflow.com/users/422597/colin-hebert","reputation":91879,"display_name":"Colin Hebert"},"content_license":"CC BY-SA 2.5","score":2,"post_id":3625697,"edited":false,"creation_date":1283419822,"comment_id":3808599,"body":"You should put all your exception handling in your loop."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/2b39a4a337cd772a45c78706b173313d?s=256&d=identicon&r=PG","account_id":174942,"user_type":"registered","user_id":404608,"link":"https://stackoverflow.com/users/404608/magggi","reputation":1145,"display_name":"Magggi","accept_rate":14},"content_license":"CC BY-SA 2.5","score":0,"post_id":3625697,"edited":false,"creation_date":1283419366,"comment_id":3808546,"body":"I am aware of that. Problem: 1.My application processes multiple files.          2.Any of the files can fail while processing.(exception)          3.But now my application exits wen any 1 file fails.          4.I want my application ot continue executing other files.So how should i structure my exception handling?"},{"owner":{"profile_image":"https://www.gravatar.com/avatar/bcdff3f230bd68f245c024dbb7b509e4?s=256&d=identicon&r=PG","account_id":37161,"user_type":"registered","user_id":106189,"link":"https://stackoverflow.com/users/106189/jim-hurne","reputation":7215,"display_name":"Jim Hurne","accept_rate":89},"content_license":"CC BY-SA 2.5","score":0,"post_id":2792758,"edited":false,"creation_date":1273437406,"comment_id":2836512,"body":"+1 for storing error codes as exception members and the idea of an &quot;error reporting&quot; framework. I accepted Loren&#39;s answer because he better defined when it is appropriate to use error codes. This answer excellently describes how to best use and implement error codes."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/bcdff3f230bd68f245c024dbb7b509e4?s=256&d=identicon&r=PG","account_id":37161,"user_type":"registered","user_id":106189,"link":"https://stackoverflow.com/users/106189/jim-hurne","reputation":7215,"display_name":"Jim Hurne","accept_rate":89},"content_license":"CC BY-SA 2.5","score":1,"post_id":2792895,"edited":false,"creation_date":1273437217,"comment_id":2836506,"body":"Thanks! Your criteria for when to use error codes is excellent. The system I had this question in mind for does need to communicate with external systems, so we&#39;ll probably use error codes at the boundry."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/3445f56229632874a44596385ed6d40c?s=256&d=identicon&r=PG","account_id":113401,"user_type":"registered","user_id":298661,"link":"https://stackoverflow.com/users/298661/puppy","reputation":145171,"display_name":"Puppy","accept_rate":82},"content_license":"CC BY-SA 2.5","score":0,"post_id":2795070,"edited":false,"creation_date":1273408952,"comment_id":2834678,"body":"It&#39;s much easier for a user to remember Error 666- especially if these codes are cross-language. If you gave a natural language description, you&#39;d have to translate it into six trillion languages, and when you got them back, you&#39;d still not be sure wtf went wrong."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/02e1e5ac4f5c3e32859dede277dfd64b?s=256&d=identicon&r=PG","account_id":6356,"user_type":"registered","user_id":10659,"link":"https://stackoverflow.com/users/10659/loren-pechtel","reputation":8963,"display_name":"Loren Pechtel","accept_rate":51},"content_license":"CC BY-SA 2.5","score":0,"post_id":2795070,"edited":false,"creation_date":1273371967,"comment_id":2833169,"body":"You can do both--start with an error code and then give a text description: Error 404 -- Page not found."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/1aa48f7606f5b08595b0a0356a61e8b6?s=256&d=identicon&r=PG","account_id":28542,"user_type":"registered","user_id":76337,"link":"https://stackoverflow.com/users/76337/john-saunders","reputation":160920,"display_name":"John Saunders","accept_rate":70},"content_license":"CC BY-SA 2.5","score":0,"post_id":2792895,"reply_to_user":{"profile_image":"https://www.gravatar.com/avatar/3e9f1629fd4cb4a5ce9fbd27b13e862d?s=256&d=identicon&r=PG","account_id":55,"user_type":"registered","user_id":67,"link":"https://stackoverflow.com/users/67/rex-m","reputation":142554,"display_name":"Rex M","accept_rate":91},"edited":false,"creation_date":1273349403,"comment_id":2832069,"body":"@Rex: it would be more accurate to say, &quot;Exceptions may not always propagate beyond a program&quot;."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/1aa48f7606f5b08595b0a0356a61e8b6?s=256&d=identicon&r=PG","account_id":28542,"user_type":"registered","user_id":76337,"link":"https://stackoverflow.com/users/76337/john-saunders","reputation":160920,"display_name":"John Saunders","accept_rate":70},"content_license":"CC BY-SA 2.5","score":0,"post_id":2792746,"reply_to_user":{"profile_image":"https://www.gravatar.com/avatar/7035191aae631e8c22594242ce3edd50?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":43031,"user_type":"registered","user_id":125601,"link":"https://stackoverflow.com/users/125601/robert-fraser","reputation":10689,"display_name":"Robert Fraser","accept_rate":90},"edited":false,"creation_date":1273349351,"comment_id":2832064,"body":"@Robert: I know that an error code may be present. This is especially true when the exception was thrown by a wrapper around a legacy application that uses error codes. Examples are any exceptions from calling Win32 (HRESULT) or COM, or SqlException, which contains SQL Server error codes."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/3e9f1629fd4cb4a5ce9fbd27b13e862d?s=256&d=identicon&r=PG","account_id":55,"user_type":"registered","user_id":67,"link":"https://stackoverflow.com/users/67/rex-m","reputation":142554,"display_name":"Rex M","accept_rate":91},"content_license":"CC BY-SA 2.5","score":2,"post_id":2792895,"reply_to_user":{"profile_image":"https://www.gravatar.com/avatar/1aa48f7606f5b08595b0a0356a61e8b6?s=256&d=identicon&r=PG","account_id":28542,"user_type":"registered","user_id":76337,"link":"https://stackoverflow.com/users/76337/john-saunders","reputation":160920,"display_name":"John Saunders","accept_rate":70},"edited":false,"creation_date":1273347853,"comment_id":2831969,"body":"@John as a generalization it is reasonably accurate."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/7035191aae631e8c22594242ce3edd50?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":43031,"user_type":"registered","user_id":125601,"link":"https://stackoverflow.com/users/125601/robert-fraser","reputation":10689,"display_name":"Robert Fraser","accept_rate":90},"content_license":"CC BY-SA 2.5","score":0,"post_id":2792746,"edited":false,"creation_date":1273346166,"comment_id":2831868,"body":"-1. Faults/exceptions themselves may contain an error code. &quot;Error codes&quot; may not just be direct method returns."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/9fff4f25c9a1518d30a2ce7d130f7501?s=256&d=identicon&r=PG","account_id":34561,"user_type":"registered","user_id":97745,"link":"https://stackoverflow.com/users/97745/crowne","reputation":8464,"display_name":"crowne","accept_rate":86},"content_license":"CC BY-SA 2.5","score":2,"post_id":2795070,"edited":false,"creation_date":1273344930,"comment_id":2831770,"body":"Thats not very user friendly, see Loren&#39;s answer above. Codes should be fed to other systems, humans should be presented with natural language descriptions rather than ...    &quot;WTF is error 666? Sounds bad but I have no idea what it means&quot;"},{"owner":{"profile_image":"https://www.gravatar.com/avatar/4e4970688774a749d9212ed9c55fcc38?s=256&d=identicon&r=PG","account_id":127699,"user_type":"registered","user_id":325042,"link":"https://stackoverflow.com/users/325042/winesoaked","reputation":1475,"display_name":"WineSoaked"},"content_license":"CC BY-SA 2.5","score":0,"post_id":2793317,"edited":false,"creation_date":1273338349,"comment_id":2831400,"body":"A lot of these existing services don&#39;t use SOAP, and predate my arrival at my firm. I just do what I can with what I was handed."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/1aa48f7606f5b08595b0a0356a61e8b6?s=256&d=identicon&r=PG","account_id":28542,"user_type":"registered","user_id":76337,"link":"https://stackoverflow.com/users/76337/john-saunders","reputation":160920,"display_name":"John Saunders","accept_rate":70},"content_license":"CC BY-SA 2.5","score":0,"post_id":2793317,"edited":false,"creation_date":1273326711,"comment_id":2830763,"body":"Your customers don&#39;t deal with SOAP Faults? Interesting."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/1aa48f7606f5b08595b0a0356a61e8b6?s=256&d=identicon&r=PG","account_id":28542,"user_type":"registered","user_id":76337,"link":"https://stackoverflow.com/users/76337/john-saunders","reputation":160920,"display_name":"John Saunders","accept_rate":70},"content_license":"CC BY-SA 2.5","score":1,"post_id":2792895,"edited":false,"creation_date":1273326644,"comment_id":2830760,"body":"Exceptions may propagate out of a web service as faults, so your statement is not accurate."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/1aa48f7606f5b08595b0a0356a61e8b6?s=256&d=identicon&r=PG","account_id":28542,"user_type":"registered","user_id":76337,"link":"https://stackoverflow.com/users/76337/john-saunders","reputation":160920,"display_name":"John Saunders","accept_rate":70},"content_license":"CC BY-SA 2.5","score":0,"post_id":2792746,"edited":false,"creation_date":1273326572,"comment_id":2830754,"body":"The error code returned by, for instance, <code>TryParse</code> is not a good example of an error code. It&#39;s only true/false. It is unnecessary to assign a separate error code to each possible reason for a method to fail."},{"owner":{"profile_image":"https://i.stack.imgur.com/rX1ss.png?s=256&g=1","account_id":36215,"user_type":"registered","user_id":103167,"link":"https://stackoverflow.com/users/103167/ben-voigt","reputation":279358,"display_name":"Ben Voigt","accept_rate":53},"content_license":"CC BY-SA 2.5","score":2,"post_id":2792746,"edited":false,"creation_date":1273287138,"comment_id":2829139,"body":"Exceptions have no difficult at all carrying detail.  Where error codes are appropriate is when the caller might reasonably be asking &quot;Is it possible to XYZ?&quot;, e.g. &quot;Is it possible to parse this string as a DateTime?&quot;.  In this case exceptions are not a good way to report failure.  Error codes are best and fastest when failure is handled by the immediate caller.  Remember, it&#39;s cheaper to turn an error code into an exception than vice versa."},{"owner":{"profile_image":"https://www.gravatar.com/avatar/835888be611e37e818894e5133b005b4?s=256&d=identicon&r=PG","account_id":15190,"user_type":"registered","user_id":31828,"link":"https://stackoverflow.com/users/31828/james-van-huis","reputation":5491,"display_name":"James Van Huis"},"content_license":"CC BY-SA 2.5","score":40,"post_id":1070593,"edited":false,"creation_date":1246472637,"comment_id":883118,"body":"Note: if you are using Eclipse, simply write &#39;throw new &lt;CustomName&gt;Exception&#39;, and then use the Autofix (Ctrl+1).  This will create a new class for you which extends Exception, and contains the boilerplate code."}]